### ISSUE TITLE
[Feature] Search page

### ISSUE THREAD

**Issue by moritzkirstein** [deltaDAO/mvg-catalogue#9]
## Motivation / Problem
A search page needs to be implemented

## Solution
- [ ] Basic design according to Figma
- [ ] Filter for type in place ("all"  -> default, "algorithm", "dataset")
- [ ] Sort by filter in place ("relevance" -> default, "created", "updated")
- [ ] Result per page filter in place ("10" -> default, "25", "50")

**Comment by LucaMilanese90** [comment]
@moritzkirstein Do these filters have a dropdown when clicked to choose between the different options or are they cycling between options at every click?

**Comment by moritzkirstein** [comment]
I do prefer a dropdown solution to select the different options
